### ISSUE TITLE
Feature Request: Ability to move Overlay to Center

### ISSUE THREAD

**Issue by Darkosto** [xt9/DeepMobLearning#10]
Hello!

Would you consider adding a feature to allow the overlay to be placed in the center section of the screen and not just the corners? For example "centerleft", "centerright"?

Thanks!
DarkSoada!

**Comment by xt9** [comment]
I'm really busy IRL atm so might not be able to add the feature right away, but it's certainly something I could add.

I saw the clash with the matter overdrive overlay on your stream so I understand the need for this, however my preference would be adding options for manual padding, so for example you can have 'topleft' and then a top padding of '20' so it would still be on that side, but further down so it does not overlap with the MO gui. 

How does that sound?

**Comment by xt9** [comment]
So I did play around with this a bit.
Added 2 config fields for horizontal and vertical padding. Which can take negative values, so if you wanted it closer on the edge on the left side you could set `horizontalSpacing` to `-5`.
In the following example I have a positive vertical value which makes it go further down on the screen, and a positive horizontal value that makes it go further to the right.

Personally I think this is a pretty good solution since people can manually do their positioning so it fits their game ui scale.

![Fields](https://i.imgur.com/xHPSfU4.png)

Which results in this

![Overlay](https://i.imgur.com/BD0wKio.png)

**Comment by Darkosto** [comment]
Yeah, I like that a lot. That would work for me.

Thanks!

**Comment by xt9** [comment]
Cool, I'll get this pushed to Curseforge as soon as possible.
