### ISSUE TITLE
[Bug] Overflow causing trial to be unfinishable

### ISSUE THREAD

**Issue by nyasara** [xt9/DeepMobLearning#47]
When running a trial, somehow I am managing to "overkill" and the "Enemies left" counter goes to negative numbers, and the wave never finishes. I believe this might be because I have AoE damage on through Astral Sorcery? All I know is that I've tried three trials now and every time this happens, usually around wave 5 or 6.

Modpack: FTB Interactions

**Comment by Terrandel** [comment]
I just wanted to drop a note to say I am seeing this as well. for me it's happening also on either wave 5 or 6 on modpack 'Absolute Mek' - I believe this is happening because its glitching out spawned special mobs (using zombie for instance, special mobs with effects glitch into the floor, then when killed count toward the kill counter too far resulting in a negative number)

I think this negative number issue can be resolved by changing the complete check to check for any negative numbers as well and autocomplete that wave if the negative number is present.

**Comment by NathanPB** [comment]
This thread is pretty old, but I managed to come with a fix: https://github.com/NathanPB/DeepMobLearning/releases/tag/1.12.2-2.0.1-nathanpbfix

Since the repository does not seems to be active anymore and the source code has no license, I published it by my own in my fork. If the mod author wants to I can remove it

**Comment by xt9** [comment]
@NathanPB You're good to keep the fork, and I'll try to review the PR when I have the chance.

**Comment by xt9** [comment]
Fixed in febe2e8

**Comment by xt9** [comment]
@NathanPB Thank you for the PR
