### ISSUE TITLE
[Mod support] Resquesting support for mods

### ISSUE THREAD

**Issue by YaibaToKen** [xt9/DeepMobLearning#7]
As I was told in another issue, support will be provided for mods, on request.
I'd like to request support for a few mods:

- ~~Thermal Foundation (it hads 3 mobs based on Blazes);~~

- Ice and Fire (this one might be more annoying as it would be best to keep the dragons limited to their own data model);

- ~~Tinker's Construct (different kinds of slimes);~~

- Cyberware (I believe the new project on Curse is called Robotic Parts) for the Cyberzombies;

**Comment by xt9** [comment]
Thermal support already exists and is enabled whenever thermal foundation is loaded.

I've had requests for the Tcon slimes before, so I'll add that.

Will have to take a look at cyberware and Ice and fire before deciding if I should group multiple mobs from those in a single data model.

**Comment by YaibaToKen** [comment]
Might make sense to add the Cyberzombie to the regular Zombie data model. Sorry, didn't notice the Thermal Foundation Support.

**Comment by xt9** [comment]
No problem, I should probably list all supported mods on the description of the project.

**Comment by xt9** [comment]
Tinker's construct blue slime model added in https://github.com/xt9/DeepMobLearning/commit/5fba7cac044820442bdfb945d2764e3021854330

I took a quick look at cyberware, I guess the support would be for Robotic parts which is the 1.12 port. oh you even wrote that. If it's just one mob I could probably make a small commit for that soon.

Ice and fire is gonna have to be some weekend project, since it adds so many mobs.

**Comment by NanayaQ** [comment]
Is there any plans for adding more minecraft regular hostile mob such as:
Elder Guardian
Guardian
Evoker
Stray
Vex
Shulker
Endermite
Silverfish

Also I would like to request a mod as well if possible from
Botania: Gaia guardian (Just mainly Gaia Guardian first phase boss since after 40+ kill or so it just get boring to do once in a while when farming for materials and also for automation purposes!)

**Comment by xt9** [comment]
Strays would count for the Skeleton if it wasn't for the fact that they extend AbstractSkeleton instead of just EntitySkeleton, but could add a clause for that.

Endermite, Silverfish & Evokers probably won't happen due to being to rare or having so small loottables.

Guardians & Vex/Shulkers should be added, they were just forgotten in the first versions of the mod.

I'm tempted to take you up on making one for the Gaia guardian, but I have very big respect for Vazkii's effort to make it non-automatable, and if you have to farm it in the first place it's probably due to bad modpack design (Like ProjectOzone2 was a great pack but forcing people to farm Guardians is just wrong)

**Comment by NanayaQ** [comment]
I will look forward to the Guardians (sometime I find myself have to go 2000 ~ 7500 chuck just to look for a water temple in the ocean, bad RNG I guess =.=), Vex, and Shulkers since they are primary to what I need because of specific drop from other mod such as Reliquary etc...

And as for the Gaia Guardian I didn't have much hope for when I was writing it up so when I learn about redstone arsenal specially the Bow and Quiver I found a way to make it enjoyable.

**Comment by xt9** [comment]
Working on a bigger Feature for the mod, so this is put on the back burner for now. ⚗️

**Comment by xt9** [comment]
Shulker & Guardian data models are added in a dev build and will be out whenever the feature I'm working on is complete. Cyberware & Ice and Fire is still on the back burner.

**Comment by YaibaToKen** [comment]
@Could I ask if there are news regarding this? Or should I consider making a PR?

**Comment by hron84** [comment]
I would like to add Embers golems and Thaumcraft Wisps, Crabs and potentially Crimson guys to the list. Embers golems are just boring to farm and their drop table is quite small, Wisps would be hard since they drop random Vis Crystals, Crabs are for ender pearl IIRC and Crimson Knight/Cultists are for their armor, void seed and that strange book.

All loot tables are quite small but supporting them would just improve QoL.

**Comment by xt9** [comment]
1.12 Will recieve no further features/integrations
