### ISSUE TITLE
[Suggestion / Discussion] Splitting the Trials feature into its own mod

### ISSUE THREAD

**Issue by T145** [xt9/DeepMobLearning#9]
DML is pretty great, but there are some problems I see in it. The motto for the mod is "Server friendly mob loot acquisition," but I feel like the new Trials feature counters the entire purpose of the mod. It's really well made, but since it doesn't quite fit DML as a whole, I think it should be split off into its own mod. Also in the realm of performance, the particle FX generated when crafting those Glitch Ingots should be toned down to something like the level of AE2.

The other issue I have is the excess of useless crafting ingredient items. I find myself crafting a lot of materials I don't really use elsewhere (i.e. dyes and glass panes). Making things more generic would help. Renaming some of those items would be good too. Like instead of Glitch Hearts you could just expand on the concept of stable and unstable Glitch Fragments. Having the Unstable Glitch Fragments look more like a crystalline shard instead of dust would be a nice touch.

My next suggestion would be to remove essences as a whole, and instead just have their results dropped randomly. The quality and amount of the drops (as well as their drop chances) could be configurable, as well as restricted by model tier. Doing this would make the mod feel more like a mob grinder, and remove the necessity for essence items and the Loot Fabricator. The Simulation Chamber would need a GUI redesign to accommodate this, but I'm sure it wouldn't be hard at all. Since you only have two machines, the machine casing item could also be removed. This would also take a lot of the burden off you to optimize everything for mod support, b/c if something is a bit off or not fitting someone's playstyle they could just change it in the config.

I've seen that you're making an experimental Blood Magic addon, and am confused as to why this isn't in the base mod. Instead of checking if the Blood Magic addon is installed on DML's side, just check for Blood Magic and add in the items and blocks if it's present.

I can tell you've put a lot of work into this based on the amount of public polish, which I respect. There seems to be a bit of a disconnect w/ the community in regards to this mod, and hopefully some of these changes can prevent that.

Keep up the great work!

**Comment by xt9** [comment]
### Thank you for the feedback, I appreciate that you've taken the time to put your thoughts into writing.

> but I feel like the new Trials feature counters the entire purpose of the mod

It's optional, and it's a controlled system, it can in no way spiral out of control in any comparison to a mob farm with thousands of mob/item entities causing a server crash. It adds additional incentive to fight monsters yourself and I'm pretty happy with how it fits with the other parts of the mod.

Servers with in-world mob farms have no safeguards from players who aren't experienced enough to deal with item overflows or mob overflow from that's caused by their kill mechanic failing or item collection method being insufficient.

The trial feature might need a few more killswitches in place like a maximum duration etc. but in no way can I compare it to an in-world mob farm, they're just too different.

> The other issue I have is the excess of useless crafting ingredient items. I find myself crafting a lot of materials I don't really use elsewhere (i.e. dyes and glass panes).

I agree with this point, I think I originally wanted a lot thematically correct ingredients for the machines and Deep Learner since they all had very vibrant tints and I wanted to keep it realistic. I should take a second look at the existing recipes and try removing some the more uncommon ingredients.  

I do however disagree with that the mod has too many ingredients, the soot-covered crafting and the crafting process for the glitch ingots are separated from each other and when a player reaches either point they should not feel like it's too microcrafty, it's not the least microcrafting heavy mod out there, but it's far from the worst.

> My next suggestion would be to remove essences as a whole.

Nope, that's not going to happen. Thanks for the input but I'm very happy with the flow as it is now.

> I've seen that you're making an experimental Blood Magic addon, and am confused as to why this isn't in the base mod. Instead of checking if the Blood Magic addon is installed on DML's side, just check for Blood Magic and add in the items and blocks if it's present.

I've done this previously for the mod compat where I check if something is loaded, and you're right it could totally be in the base mod, but I wanted to avoid bloat and I had no idea what size the BM mod would be so I separated it out from the base mod early.

In the end it wasn't that big and when I have the time I might merge it back into the main mod.
